UAV1:
  r1:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10
  
  r2:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10
  
  r3:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r4:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r5:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r6:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r7:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r8:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r9:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  r10:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10

  h:
    scout1: 0.0
    scout2: 5.3
    scout3: 5.3
    scout4: 5.3
    scout5: 2.3
    scout6: 5.3
    scout7: 5.3
    scout8: 5.3
    scout9: 5.3
    scout10: 5.3
    end: 10
